name: Verdaccio Website CI

on:
  workflow_dispatch:
  pull_request:
    paths:
        - 'website/**'
        - './.github/workflows/website.yml'
  schedule:
    - cron: '0 0 * * *' 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Use Node 16
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # tag=v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # tag=v2.2.2
        with:
          version: 6.32.15
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - name: Build Plugins
        run: pnpm build --filter "docusaurus-plugin-contributors"
      - name: Cache Docusaurus Build
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # tag=v3
        with:
          path: website/node_modules/.cache/webpack
          key: cache/webpack-${{github.ref}}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: cache/webpack-${{github.ref}}

 
